#!/usr/bin/perl -w
use FindBin;
use lib $FindBin::Bin;
##
#########################################################
use strict;
use Bible;

                                        #globals, program info
use vars qw($myname $ver $id_line);
($myname = $0) =~ s!(.*)/!!;
my $working_dir = $1;
if (!$working_dir) {$working_dir = "\.";}
($ver = '$Revision: 1.1 $') =~ s!.*: (\d+\.\d+).*!$1!;
$|=1;					#flush buffers immediately

                                        #parse input arguments
my @inputs = @ARGV;
my $fh;
open $fh, ">/tmp/asdf";
print $fh @inputs;
my ($commandline,$filename) = 0;
parse_args();

                                        #redirect input
if ($commandline) {
   my $inputs = '';
   foreach (@inputs) {
     $inputs .= " $_";
   }
   $inputs =~ s/(\d+)\s+(\w+)/\"$1 $2\"/;
   my $command = "$working_dir/cmextractb $inputs";
   print STDERR "Calling: $command\n" if $debug;
   exec ($command);
} else { 
   my $inputs = '';
   foreach (@inputs) {
     $inputs .= " $_";
   }
   $inputs =~ s/(\d+)\s+(\w+)/\"$1 $2\"/;
   my $command = "$working_dir/fextractb $inputs";
   print STDERR "Calling: $command\n" if $debug;
   if (!$filename) {
     open (CMD,"|$command");
     while (<STDIN>) {print CMD $_;}
   } else {
     exec ($command);
   }
}

##################################

sub usage { 
  print <<EOL;
Usage for $myname (version $ver):
     $myname --book <book> --chapter <chapter> --verse <verse>
     (or) -b <book>
     (or) -b <book-book>
     (or) -b <book> -c <chapter>
     (or) -b <book> -c <chapter-chapter>
     (or) -b <book> -c <chapter> -v <verse-verse>
     (or) --range <ot,nt,let,whl,gos,wis>
     (or) < <input file>
     (or) -f <input file>

Specific Optional Flags:
    --translation  <translation>
EOL
   my $counter=0;
   initTranslations();
   print  "        ";
   foreach (@translations) {
     print  " $_";
     $counter++;
     if ($counter == 6) { print "\n        "; $counter = 0;}
   }
   print "\n";
die <<EOF
    --language <english(default), spanish,german>

Output Flags: 
     --raw (just text)
     --showverse (output with verse,chapter,book delination)
     --normal (for input to other programs (default))

General Optional Flags:
    --debug
    --help
    --swap_dir <swap_dir> (default:$swap_dir)
    --kill (kill the expanded library file (delete it after use))
EOF
} #end usage

##################################

sub parse_args {
    use Getopt::Long;

    my ($showhelp,$tmp);
 
    my $language; 
    my ($raw,$byverse,$format,$normal);

    GetOptions("book=s"          => \$commandline,
               "start=i"         => \$commandline,
               "filename=s"      => \$filename,
               "stop=i"          => \$commandline,
               "chapter=s"       => \$commandline,
               "verse=s"         => \$commandline,
               "range=s"         => \$commandline,
               "end"             => \$tmp,
               "translation=s"   => \$tmp,
               "language=s"      => \$language,
               "swap_dir=s"      => \$swap_dir,
               "raw"             => \$raw,
               "showverse"         => \$byverse,
               "normal"          => \$normal,
               "kill"            => \$tmp,
               "debug"         => \$debug,
               "help"            => \$showhelp )
              || ($showhelp = 1);

    if (! -d $swap_dir) {$showhelp =1;}
                                   #required arguments
    if ($showhelp) { &usage(); }

}


